library(shinydashboard)

dashboardPage(
  dashboardHeader(title = "iTag"),
  dashboardSidebar(),
  dashboardBody(
    fluidRow(
      box(width = 2, height = 4,
          selectInput(inputId = "pr", "Planned or Responsive",
                      c("Planned" = "planned",
                        "Responsive" = "responsive")),
          selectInput(inputId = "channel", "Channel",
                      c("PPC" = "ppc",
                        "Outbrain" = "outbrain",
                        "Taboola" = "taboola",
                        "Trueview" = "trueview",
                        "Display" = "display",
                        "Facebook" = "facebook",
                        "YouTube" = "youtube",
                        "Twitter" = "twitter",
                        "linkedin" = "linkedin")),
          conditionalPanel("input.channel == 'ppc'", 
                           selectInput(inputId = "po", "Paid / Organic",c("Paid" = "paid")),
                           selectInput(inputId = "format", 
                                       "Channel Format",c("PPC" = "ppc", "Other" = "other"))),
          conditionalPanel("input.channel == 'outbrain'", 
                           selectInput(inputId = "po", "Paid / Organic",c("Paid" = "paid")),
                           selectInput(inputId = "format", 
                                       "Channel Format",c("Advertorial" = "advertorial",
                                                          "Other" = "other"))),
          conditionalPanel("input.channel == 'taboola'", 
                           selectInput(inputId = "po", "Paid / Organic",c("Paid" = "paid")),
                           selectInput(inputId = "format", 
                                       "Channel Format",c("Advertorial" = "advertorial",
                                                          "Other" = "other"))),
          conditionalPanel("input.channel == 'trueview'", 
                           selectInput(inputId = "po", "Paid / Organic",c("Paid" = "paid")),
                           selectInput(inputId = "format", 
                                       "Channel Format",c("In-Stream" = "instream",
                                                          "In-Display" = "indisplay",
                                                          "Other" = "other"))),
          conditionalPanel("input.channel == 'display'", 
                           selectInput(inputId = "po", "Paid / Organic",c("Paid" = "paid")),
                           selectInput(inputId = "format", 
                                       "Channel Format",c("Banner" = "banner",
                                                          "Other" = "other"))),
          conditionalPanel("input.channel == 'facebook'", 
                           selectInput(inputId = "po", "Paid / Organic",c("Paid" = "paid",
                                                                          "Organic" = "organic")),
                           selectInput(inputId = "format", 
                                       "Channel Format",c("Other" = "other"))),
          conditionalPanel("input.channel == 'youtube'", 
                           selectInput(inputId = "po", "Paid / Organic",c("Paid" = "paid",
                                                                          "Organic" = "organic")),
                           selectInput(inputId = "format", 
                                       "Channel Format",c("Video" = "video",
                                                          "Profile" = "profile",
                                                          "Other" = "other"))),
          conditionalPanel("input.channel == 'twitter'", 
                           selectInput(inputId = "po", "Paid / Organic",c("Paid" = "paid",
                                                                          "Organic" = "organic")),
                           selectInput(inputId = "format", 
                                       "Channel Format",c("Tweet" = "tweet",
                                                          "Other" = "other"))),
          conditionalPanel("input.channel == 'linkedin'", 
                           selectInput(inputId = "po", "Paid / Organic",c("Paid" = "paid",
                                                                          "Organic" = "organic")),
                           selectInput(inputId = "format", 
                                       "Channel Format",c("Articles" = "articles",
                                                          "Profile" = "profile",
                                                          "Other" = "other")))
          
          ),
      
      box(width = 2, height = 4,
          selectInput(inputId = "product", "Product",
                      c("All" = "all",
                        "CHI" = "chi",
                        "CHC" = "chc",
                        "Energy" = "energy",
                        "Landlords" = "landlords")),
          selectInput(inputId = "campaign", "Campaign Name",
                      c("C1" = "c1",
                        "C2" = "c2",
                        "C3" = "c3",
                        "C4" = "c4",
                        "C5" = "c5")),
          
          textInput(inputId = "url", label = "URL"),
          radioButtons(inputId = "creative", "Creative", selected = "no",
                       c("Yes" = "yes",
                         "No" = "no")),
          conditionalPanel("input.creative == 'yes'", 
                           textInput(inputId = "cname", "Creative Name"),
                           radioButtons(inputId = "bbb", 
                                       "Build / Borrow / Buy",c("Build" = "build",
                                                          "Borrow" = "borrow",
                                                          "Buy" = "buy")))
      )
    )
  )
)